# Generated by Django 2.2.19 on 2023-06-14 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Устройство')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Описание(Пимечание)')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Населенный пункт')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Описание(Пимечание)')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подразделение')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('num', models.CharField(max_length=5, verbose_name='Номер дома')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='bid.Location', verbose_name='Населеный пункт')),
            ],
            options={
                'verbose_name': ('Подразделение',),
                'verbose_name_plural': ('Подразделения',),
                'ordering': ('title', 'location'),
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Опишите проблему', verbose_name='Заявка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('image', models.ImageField(blank=True, help_text='Вы можете загрузить изображение', upload_to='bid/', verbose_name='Картинка')),
                ('device', models.ForeignKey(blank=True, help_text='Укажите устройство', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='bid.Device', verbose_name='Устройство')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-pub_date',),
            },
        ),
    ]
