# Generated by Django 2.2.19 on 2023-06-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_auto_20230614_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='Штатный', max_length=40, unique=True, verbose_name='Уровень важности')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Описание(Пимечание)')),
            ],
            options={
                'verbose_name': 'Уровень важности',
                'verbose_name_plural': 'Уровни важности',
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('fathers_name', models.CharField(max_length=40, verbose_name='Отчество')),
                ('dob', models.DateTimeField(verbose_name='Дата рождениия')),
            ],
            options={
                'verbose_name': 'Сотрудник отдела',
                'verbose_name_plural': 'Сотрудники отдела',
                'ordering': ('last_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Описание(Пимечание)')),
                ('bid', models.ForeignKey(default='NULL', help_text='Укажите обрабатываемую заявку', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='controls', to='bid.Bid', verbose_name='Заявка')),
                ('level', models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='controls', to='bid.Level', verbose_name='Уровень важности')),
                ('worker', models.ForeignKey(default='NULL', help_text='Укажите ответсвенного сотрудника', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='controls', to='bid.Worker', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Обработка заявки',
                'verbose_name_plural': 'Обработка заявок',
                'ordering': ('bid',),
            },
        ),
    ]
