# Generated by Django 2.2.19 on 2023-06-16 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_control_level_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, unique=True, verbose_name='Статус')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Описание(Пимечание)')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ('status',),
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='bid.Status', verbose_name='Статус'),
        ),
    ]
