# Generated by Django 2.2.19 on 2023-06-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_auto_20230616_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='bid',
            field=models.ForeignKey(default='NULL', help_text='Укажите обрабатываемую заявку', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='bid.Bid', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='control',
            name='worker',
            field=models.ForeignKey(default='NULL', help_text='Укажите ответсвенного сотрудника', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='controls', to='bid.Worker', verbose_name='Ответсвенный сотрудник'),
        ),
    ]
