# Generated by Django 2.2.19 on 2023-06-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_auto_20230616_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.ForeignKey(blank=True, help_text='ПОСЛЕ ОБРАБОТКИ ЗАПРОСА ПОМЕНЙТЕ СТАТУС!!!', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='bid.Status', verbose_name='Статус'),
        ),
    ]
