# Generated by Django 2.2.19 on 2023-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_auto_20230616_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='dob',
            field=models.DateField(verbose_name='Дата рождениия'),
        ),
    ]
